name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - id: install-pipenv
      name: Install pipenv
      run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv
          python -m pip install --no-cache-dir requests
      shell: bash
      
    - name: Run scrapers
      run: python scrape.py > data.json
      
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
